openapi: 3.1.0
info:
  description: Anything that you can achieve with PDFs, presence, and persistence in a bank branch you can do with our API. We've always wanted a fully programmatic bank so we built one. Our API faithfully exposes the data and capabilities of the Federal Reserve, Visa, The Clearing House, depository networks, and accounting tools. It's lovingly boring and exceptionally powerful. If you have any questions or want to get started, don't hesitate to ping us at sales@increase.com. We can't wait to see what you build!
  title: Increase Account Numbers Swift Transfers API
  version: 0.0.1
servers:
- url: https://api.increase.com
- url: https://sandbox.increase.com
security:
- bearerAuth: []
tags:
- description: Swift Transfers send funds internationally.
  name: Swift Transfers
paths:
  /swift_transfers:
    get:
      operationId: list_swift_transfers
      parameters:
      - in: query
        name: cursor
        required: false
        schema:
          description: Return the page of entries after this one.
          type: string
          x-documentation-priority: low
      - in: query
        name: limit
        required: false
        schema:
          description: Limit the size of the list that is returned. The default (and maximum) is 100 objects.
          minimum: 1
          type: integer
          x-documentation-priority: low
      - example: account_in71c4amph0vgo2qllky
        in: query
        name: account_id
        required: false
        schema:
          description: Filter Swift Transfers to those that originated from the specified Account.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Accounts
      - in: query
        name: idempotency_key
        required: false
        schema:
          description: Filter records to the one with the specified `idempotency_key` you chose for that object. This value is unique across Increase and is used to ensure that a request is only processed once. Learn more about [idempotency](https://increase.com/documentation/idempotency-keys).
          maxLength: 200
          minLength: 1
          type: string
          x-documentation-priority: default
      - in: query
        name: status.in
        required: false
        schema:
          description: Return results whose value is in the provided list. For GET requests, this should be encoded as a comma-delimited string, such as `?in=one,two,three`.
          items:
            enum:
            - pending_approval
            - canceled
            - pending_reviewing
            - requires_attention
            - pending_initiating
            - initiated
            - rejected
            - returned
            type: string
            x-enum-descriptions:
            - The transfer is pending approval.
            - The transfer has been canceled.
            - The transfer is pending review by Increase.
            - The transfer requires attention from an Increase operator.
            - The transfer is pending initiation.
            - The transfer has been initiated.
            - The transfer has been rejected by Increase.
            - The transfer has been returned.
          type: array
          x-documentation-priority: default
        explode: false
      - in: query
        name: created_at.after
        required: false
        schema:
          description: Return results after this [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp.
          format: date-time
          type: string
          x-documentation-priority: low
      - in: query
        name: created_at.before
        required: false
        schema:
          description: Return results before this [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp.
          format: date-time
          type: string
          x-documentation-priority: low
      - in: query
        name: created_at.on_or_after
        required: false
        schema:
          description: Return results on or after this [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp.
          format: date-time
          type: string
          x-documentation-priority: low
      - in: query
        name: created_at.on_or_before
        required: false
        schema:
          description: Return results on or before this [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp.
          format: date-time
          type: string
          x-documentation-priority: low
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/swift_transfer_list'
          description: Swift Transfer List
        4XX:
          $ref: '#/components/responses/errorResponse'
        5XX:
          $ref: '#/components/responses/errorResponse'
      summary: List Swift Transfers
      x-sandbox-only: false
      x-tag: Swift Transfers
      tags:
      - Swift Transfers
    post:
      operationId: create_a_swift_transfer
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_a_swift_transfer_parameters'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/swift_transfer'
          description: Swift Transfer
        4XX:
          $ref: '#/components/responses/errorResponse'
        5XX:
          $ref: '#/components/responses/errorResponse'
      summary: Create a Swift Transfer
      x-sandbox-only: false
      x-tag: Swift Transfers
      tags:
      - Swift Transfers
  /swift_transfers/{swift_transfer_id}:
    get:
      operationId: retrieve_a_swift_transfer
      parameters:
      - example: swift_transfer_29h21xkng03788zwd3fh
        in: path
        name: swift_transfer_id
        required: true
        schema:
          description: The identifier of the Swift Transfer.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Swift Transfers
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/swift_transfer'
          description: Swift Transfer
        4XX:
          $ref: '#/components/responses/errorResponse'
        5XX:
          $ref: '#/components/responses/errorResponse'
      summary: Retrieve a Swift Transfer
      x-sandbox-only: false
      x-tag: Swift Transfers
      tags:
      - Swift Transfers
  /swift_transfers/{swift_transfer_id}/approve:
    post:
      operationId: approve_a_swift_transfer
      parameters:
      - example: swift_transfer_29h21xkng03788zwd3fh
        in: path
        name: swift_transfer_id
        required: true
        schema:
          description: The identifier of the Swift Transfer to approve.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Swift Transfers
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/swift_transfer'
          description: Swift Transfer
        4XX:
          $ref: '#/components/responses/errorResponse'
        5XX:
          $ref: '#/components/responses/errorResponse'
      summary: Approve a Swift Transfer
      x-sandbox-only: false
      x-tag: Swift Transfers
      tags:
      - Swift Transfers
  /swift_transfers/{swift_transfer_id}/cancel:
    post:
      operationId: cancel_a_pending_swift_transfer
      parameters:
      - example: swift_transfer_29h21xkng03788zwd3fh
        in: path
        name: swift_transfer_id
        required: true
        schema:
          description: The identifier of the pending Swift Transfer to cancel.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Swift Transfers
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/swift_transfer'
          description: Swift Transfer
        4XX:
          $ref: '#/components/responses/errorResponse'
        5XX:
          $ref: '#/components/responses/errorResponse'
      summary: Cancel a pending Swift Transfer
      x-sandbox-only: false
      x-tag: Swift Transfers
      tags:
      - Swift Transfers
components:
  schemas:
    swift_transfer:
      additionalProperties: false
      description: Swift Transfers send funds internationally.
      example:
        account_id: account_in71c4amph0vgo2qllky
        account_number: '987654321'
        amount: 100
        bank_identification_code: ECBFDEFFTPP
        created_at: '2020-01-31T23:59:59Z'
        created_by:
          category: user
          user:
            email: user@example.com
        creditor_address:
          city: Frankfurt
          country: DE
          line1: Sonnemannstrasse 20
          line2: null
          postal_code: '60314'
          state: null
        creditor_name: Ian Crease
        debtor_address:
          city: New York
          country: US
          line1: 33 Liberty Street
          line2: null
          postal_code: '10045'
          state: null
        debtor_name: National Phonograph Company
        id: swift_transfer_29h21xkng03788zwd3fh
        idempotency_key: null
        instructed_amount: 100
        instructed_currency: USD
        pending_transaction_id: pending_transaction_k1sfetcau2qbvjbzgju4
        routing_number: null
        source_account_number_id: account_number_v18nkfqm6afpsrvy82b2
        status: initiated
        transaction_id: transaction_uyrp7fld2ium70oa7oi
        type: swift_transfer
        unique_end_to_end_transaction_reference: 9a21e10a-7600-4a24-8ff3-2cbc5943c27a
        unstructured_remittance_information: Remittance information
      properties:
        account_id:
          description: The Account to which the transfer belongs.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Accounts
        account_number:
          description: The creditor's account number.
          type: string
          x-documentation-priority: default
        amount:
          description: The transfer amount in USD cents.
          type: integer
          x-documentation-priority: default
        bank_identification_code:
          description: The bank identification code (BIC) of the creditor.
          type: string
          x-documentation-priority: default
        created_at:
          description: The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time at which the transfer was created.
          format: date-time
          type: string
          x-documentation-priority: default
        created_by:
          additionalProperties: false
          description: What object created the transfer, either via the API or the dashboard.
          example:
            category: user
            user:
              email: user@example.com
          properties:
            api_key:
              anyOf:
              - additionalProperties: false
                description: If present, details about the API key that created the transfer.
                properties:
                  description:
                    anyOf:
                    - description: The description set for the API key when it was created.
                      type: string
                      x-documentation-priority: default
                    - type: 'null'
                required:
                - description
                title: Swift Transfer Transfer Creator ApiKey
                type: object
                x-documentation-priority: default
                x-event-categories: []
                x-stainless-empty-object: false
                x-title-plural: ApiKeys
              - type: 'null'
            category:
              description: The type of object that created this transfer.
              enum:
              - api_key
              - oauth_application
              - user
              type: string
              x-documentation-priority: default
              x-enum-descriptions:
              - An API key. Details will be under the `api_key` object.
              - An OAuth application you connected to Increase. Details will be under the `oauth_application` object.
              - A User in the Increase dashboard. Details will be under the `user` object.
            oauth_application:
              anyOf:
              - additionalProperties: false
                description: If present, details about the OAuth Application that created the transfer.
                properties:
                  name:
                    description: The name of the OAuth Application.
                    type: string
                    x-documentation-priority: default
                required:
                - name
                title: Swift Transfer Transfer Creator OAuthApplication
                type: object
                x-documentation-priority: default
                x-event-categories: []
                x-stainless-empty-object: false
                x-title-plural: OAuthApplications
              - type: 'null'
            user:
              anyOf:
              - additionalProperties: false
                description: If present, details about the User that created the transfer.
                properties:
                  email:
                    description: The email address of the User.
                    type: string
                    x-documentation-priority: default
                required:
                - email
                title: Swift Transfer Transfer Creator User
                type: object
                x-documentation-priority: default
                x-event-categories: []
                x-stainless-empty-object: false
                x-title-plural: Users
              - type: 'null'
          required:
          - category
          title: Swift Transfer Transfer Creator
          type: object
          x-documentation-priority: default
          x-event-categories: []
          x-stainless-empty-object: false
          x-title-plural: Transfer Creators
        creditor_address:
          additionalProperties: false
          description: The creditor's address.
          properties:
            city:
              anyOf:
              - description: The city, district, town, or village of the address.
                type: string
                x-documentation-priority: default
              - type: 'null'
            country:
              description: The two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code for the country of the address.
              type: string
              x-documentation-priority: default
            line1:
              description: The first line of the address.
              type: string
              x-documentation-priority: default
            line2:
              anyOf:
              - description: The second line of the address.
                type: string
                x-documentation-priority: default
              - type: 'null'
            postal_code:
              anyOf:
              - description: The ZIP or postal code of the address.
                type: string
                x-documentation-priority: default
              - type: 'null'
            state:
              anyOf:
              - description: The state, province, or region of the address. Required in certain countries.
                type: string
                x-documentation-priority: default
              - type: 'null'
          required:
          - line1
          - line2
          - city
          - state
          - postal_code
          - country
          title: Swift Transfer Address
          type: object
          x-documentation-priority: default
          x-event-categories: []
          x-stainless-empty-object: false
          x-title-plural: Addresses
        creditor_name:
          description: The creditor's name.
          type: string
          x-documentation-priority: default
        debtor_address:
          additionalProperties: false
          description: The debtor's address.
          properties:
            city:
              anyOf:
              - description: The city, district, town, or village of the address.
                type: string
                x-documentation-priority: default
              - type: 'null'
            country:
              description: The two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code for the country of the address.
              type: string
              x-documentation-priority: default
            line1:
              description: The first line of the address.
              type: string
              x-documentation-priority: default
            line2:
              anyOf:
              - description: The second line of the address.
                type: string
                x-documentation-priority: default
              - type: 'null'
            postal_code:
              anyOf:
              - description: The ZIP or postal code of the address.
                type: string
                x-documentation-priority: default
              - type: 'null'
            state:
              anyOf:
              - description: The state, province, or region of the address. Required in certain countries.
                type: string
                x-documentation-priority: default
              - type: 'null'
          required:
          - line1
          - line2
          - city
          - state
          - postal_code
          - country
          title: Swift Transfer Address
          type: object
          x-documentation-priority: default
          x-event-categories: []
          x-stainless-empty-object: false
          x-title-plural: Addresses
        debtor_name:
          description: The debtor's name.
          type: string
          x-documentation-priority: default
        id:
          description: The Swift transfer's identifier.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Swift Transfers
        idempotency_key:
          anyOf:
          - description: The idempotency key you chose for this object. This value is unique across Increase and is used to ensure that a request is only processed once. Learn more about [idempotency](https://increase.com/documentation/idempotency-keys).
            type: string
            x-documentation-priority: default
          - type: 'null'
        instructed_amount:
          description: The amount that was instructed to be transferred in minor units of the `instructed_currency`.
          type: integer
          x-documentation-priority: default
        instructed_currency:
          description: The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code of the instructed amount.
          enum:
          - USD
          type: string
          x-documentation-priority: default
          x-enum-descriptions:
          - United States Dollar
        pending_transaction_id:
          anyOf:
          - description: The ID for the pending transaction representing the transfer.
            type: string
            x-documentation-priority: default
            x-id-reference-to: Pending Transactions
          - type: 'null'
        routing_number:
          anyOf:
          - description: The creditor's bank account routing or transit number. Required in certain countries.
            type: string
            x-documentation-priority: default
          - type: 'null'
        source_account_number_id:
          description: The Account Number included in the transfer as the debtor's account number.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Account Numbers
        status:
          description: The lifecycle status of the transfer.
          enum:
          - pending_approval
          - canceled
          - pending_reviewing
          - requires_attention
          - pending_initiating
          - initiated
          - rejected
          - returned
          type: string
          x-documentation-priority: default
          x-enum-descriptions:
          - The transfer is pending approval.
          - The transfer has been canceled.
          - The transfer is pending review by Increase.
          - The transfer requires attention from an Increase operator.
          - The transfer is pending initiation.
          - The transfer has been initiated.
          - The transfer has been rejected by Increase.
          - The transfer has been returned.
        transaction_id:
          anyOf:
          - description: The ID for the transaction funding the transfer. This will be populated after the transfer is initiated.
            type: string
            x-documentation-priority: default
            x-id-reference-to: Transactions
          - type: 'null'
        type:
          description: A constant representing the object's type. For this resource it will always be `swift_transfer`.
          enum:
          - swift_transfer
          type: string
          x-documentation-priority: default
        unique_end_to_end_transaction_reference:
          description: The Unique End-to-end Transaction Reference ([UETR](https://www.swift.com/payments/what-unique-end-end-transaction-reference-uetr)) for the transfer.
          type: string
          x-documentation-priority: default
        unstructured_remittance_information:
          description: The unstructured remittance information that was included with the transfer.
          type: string
          x-documentation-priority: default
      required:
      - type
      - id
      - created_at
      - created_by
      - amount
      - instructed_amount
      - instructed_currency
      - account_number
      - bank_identification_code
      - routing_number
      - creditor_name
      - creditor_address
      - debtor_name
      - debtor_address
      - unstructured_remittance_information
      - unique_end_to_end_transaction_reference
      - account_id
      - source_account_number_id
      - status
      - transaction_id
      - pending_transaction_id
      - idempotency_key
      title: Swift Transfer
      type: object
      x-event-categories:
      - swift_transfer.created
      - swift_transfer.updated
      x-stainless-empty-object: false
      x-tag: Swift Transfers
      x-title-plural: Swift Transfers
    swift_transfer_list:
      additionalProperties: true
      description: A list of Swift Transfer objects.
      example:
        data:
        - account_id: account_in71c4amph0vgo2qllky
          account_number: '987654321'
          amount: 100
          bank_identification_code: ECBFDEFFTPP
          created_at: '2020-01-31T23:59:59Z'
          created_by:
            category: user
            user:
              email: user@example.com
          creditor_address:
            city: Frankfurt
            country: DE
            line1: Sonnemannstrasse 20
            line2: null
            postal_code: '60314'
            state: null
          creditor_name: Ian Crease
          debtor_address:
            city: New York
            country: US
            line1: 33 Liberty Street
            line2: null
            postal_code: '10045'
            state: null
          debtor_name: National Phonograph Company
          id: swift_transfer_29h21xkng03788zwd3fh
          idempotency_key: null
          instructed_amount: 100
          instructed_currency: USD
          pending_transaction_id: pending_transaction_k1sfetcau2qbvjbzgju4
          routing_number: null
          source_account_number_id: account_number_v18nkfqm6afpsrvy82b2
          status: initiated
          transaction_id: transaction_uyrp7fld2ium70oa7oi
          type: swift_transfer
          unique_end_to_end_transaction_reference: 9a21e10a-7600-4a24-8ff3-2cbc5943c27a
          unstructured_remittance_information: Remittance information
        next_cursor: v57w5d
      properties:
        data:
          description: The contents of the list.
          items:
            $ref: '#/components/schemas/swift_transfer'
          type: array
          x-documentation-priority: default
        next_cursor:
          anyOf:
          - description: A pointer to a place in the list. Pass this as the `cursor` parameter to retrieve the next page of results. If there are no more results, the value will be `null`.
            type: string
            x-documentation-priority: default
          - type: 'null'
      required:
      - data
      - next_cursor
      title: Swift Transfer List
      type: object
      x-event-categories: []
      x-stainless-empty-object: false
      x-title-plural: Swift Transfer Lists
    error:
      anyOf:
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 404
            type: integer
          title:
            type: string
          type:
            enum:
            - api_method_not_found_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 403
            type: integer
          title:
            type: string
          type:
            enum:
            - environment_mismatch_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          resource_id:
            description: ''
            type: string
            x-documentation-priority: default
          status:
            enum:
            - 409
            type: integer
          title:
            type: string
          type:
            enum:
            - idempotency_key_already_used_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        - resource_id
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 403
            type: integer
          title:
            type: string
          type:
            enum:
            - insufficient_permissions_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 500
            type: integer
          title:
            type: string
          type:
            enum:
            - internal_server_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          reason:
            description: ''
            enum:
            - deleted_credential
            - expired_credential
            - ip_not_allowed
            - no_credential
            - no_header
            - no_api_access
            - wrong_environment
            type: string
            x-documentation-priority: default
            x-enum-descriptions:
            - deleted_credential
            - expired_credential
            - ip_not_allowed
            - no_credential
            - no_header
            - no_api_access
            - wrong_environment
          status:
            enum:
            - 401
            type: integer
          title:
            type: string
          type:
            enum:
            - invalid_api_key_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        - reason
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 409
            type: integer
          title:
            type: string
          type:
            enum:
            - invalid_operation_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          errors:
            description: All errors related to parsing the request parameters.
            items:
              additionalProperties: true
              properties: {}
              title: ErrorsElement
              type: object
              x-event-categories: []
              x-stainless-empty-object: false
              x-title-plural: ErrorsElements
            type: array
            x-documentation-priority: default
          status:
            enum:
            - 400
            type: integer
          title:
            type: string
          type:
            enum:
            - invalid_parameters_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        - errors
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 400
            type: integer
          title:
            type: string
          type:
            enum:
            - malformed_request_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 404
            type: integer
          title:
            type: string
          type:
            enum:
            - object_not_found_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          status:
            enum:
            - 403
            type: integer
          title:
            type: string
          type:
            enum:
            - private_feature_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
      - properties:
          detail:
            anyOf:
            - type: string
            - type: 'null'
          retry_after:
            anyOf:
            - description: ''
              type: integer
              x-documentation-priority: default
            - type: 'null'
          status:
            enum:
            - 429
            type: integer
          title:
            type: string
          type:
            enum:
            - rate_limited_error
            type: string
        required:
        - type
        - title
        - detail
        - status
        type: object
        x-event-categories: []
    create_a_swift_transfer_parameters:
      additionalProperties: true
      example:
        account_id: account_in71c4amph0vgo2qllky
        account_number: '987654321'
        bank_identification_code: ECBFDEFFTPP
        creditor_address:
          city: Frankfurt
          country: DE
          line1: Sonnemannstrasse 20
          postal_code: '60314'
        creditor_name: Ian Crease
        debtor_address:
          city: New York
          country: US
          line1: 33 Liberty Street
          postal_code: '10045'
          state: NY
        debtor_name: National Phonograph Company
        instructed_amount: 100
        instructed_currency: USD
        source_account_number_id: account_number_v18nkfqm6afpsrvy82b2
        unstructured_remittance_information: New Swift transfer
      properties:
        account_id:
          description: The identifier for the account that will send the transfer.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Accounts
        account_number:
          description: The creditor's account number.
          maxLength: 34
          minLength: 1
          pattern: ^[a-zA-Z0-9]*$
          type: string
          x-documentation-priority: default
        bank_identification_code:
          description: The bank identification code (BIC) of the creditor. If it ends with the three-character branch code, this must be 11 characters long. Otherwise this must be 8 characters and the branch code will be assumed to be `XXX`.
          maxLength: 11
          minLength: 1
          pattern: ^(?<bank>[A-Z0-9]{4})(?<country>[A-Z0-9]{2})(?<location>[A-Z0-9]{2})(?<branch>[A-Z0-9]{3})?$
          type: string
          x-documentation-priority: default
        creditor_address:
          additionalProperties: false
          description: The creditor's address.
          properties:
            city:
              description: The city, district, town, or village of the address.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            country:
              description: The two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code for the country of the address.
              maxLength: 2
              minLength: 2
              type: string
              x-documentation-priority: default
            line1:
              description: The first line of the address. This is usually the street number and street.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            line2:
              description: The second line of the address. This might be the floor or room number.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            postal_code:
              description: The ZIP or postal code of the address. Required in certain countries.
              maxLength: 16
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            state:
              description: The state, province, or region of the address. Required in certain countries.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
          required:
          - line1
          - city
          - country
          type: object
          x-documentation-priority: default
          x-event-categories: []
          x-stainless-empty-object: false
        creditor_name:
          description: The creditor's name.
          maxLength: 35
          minLength: 1
          pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
          type: string
          x-documentation-priority: default
        debtor_address:
          additionalProperties: false
          description: The debtor's address.
          properties:
            city:
              description: The city, district, town, or village of the address.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            country:
              description: The two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code for the country of the address.
              maxLength: 2
              minLength: 2
              type: string
              x-documentation-priority: default
            line1:
              description: The first line of the address. This is usually the street number and street.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            line2:
              description: The second line of the address. This might be the floor or room number.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            postal_code:
              description: The ZIP or postal code of the address. Required in certain countries.
              maxLength: 16
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
            state:
              description: The state, province, or region of the address. Required in certain countries.
              maxLength: 35
              minLength: 1
              pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
              type: string
              x-documentation-priority: default
          required:
          - line1
          - city
          - country
          type: object
          x-documentation-priority: default
          x-event-categories: []
          x-stainless-empty-object: false
        debtor_name:
          description: The debtor's name.
          maxLength: 35
          minLength: 1
          pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
          type: string
          x-documentation-priority: default
        instructed_amount:
          description: The amount, in minor units of `instructed_currency`, to send to the creditor.
          minimum: 1
          type: integer
          x-documentation-priority: default
        instructed_currency:
          description: The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code of the instructed amount.
          enum:
          - USD
          type: string
          x-documentation-priority: default
          x-enum-descriptions:
          - United States Dollar
        require_approval:
          description: Whether the transfer requires explicit approval via the dashboard or API.
          type: boolean
          x-documentation-priority: default
        routing_number:
          description: The creditor's bank account routing or transit number. Required in certain countries.
          maxLength: 35
          minLength: 1
          pattern: ^[a-zA-Z0-9]*$
          type: string
          x-documentation-priority: default
        source_account_number_id:
          description: The Account Number to include in the transfer as the debtor's account number.
          type: string
          x-documentation-priority: default
          x-id-reference-to: Account Numbers
        unstructured_remittance_information:
          description: Unstructured remittance information to include in the transfer.
          maxLength: 140
          minLength: 1
          pattern: ^[a-zA-Z0-9/?:().,'+ \-]*$
          type: string
          x-documentation-priority: default
      required:
      - account_id
      - source_account_number_id
      - account_number
      - bank_identification_code
      - instructed_amount
      - instructed_currency
      - unstructured_remittance_information
      - creditor_name
      - creditor_address
      - debtor_name
      - debtor_address
      type: object
      x-event-categories: []
      x-stainless-empty-object: false
  responses:
    errorResponse:
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/error'
      description: Error
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
x-tagGroups:
- name: Accounts
  tags:
  - Accounts
  - Account Numbers
  - Account Transfers
- name: Transactions
  tags:
  - Transactions
  - Pending Transactions
  - Declined Transactions
- name: Ach Transfers
  tags:
  - ACH Transfers
  - Inbound ACH Transfers
  - ACH Prenotifications
- name: Check Transfers
  tags:
  - Check Transfers
  - Inbound Check Deposits
- name: Real Time Payments Transfers
  tags:
  - Real-Time Payments Transfers
  - Inbound Real-Time Payments Transfers
- name: Fednow Transfers
  tags:
  - FedNow Transfers
  - Inbound FedNow Transfers
- name: Swift Transfers
  tags:
  - Swift Transfers
- name: Wire Transfers
  tags:
  - Wire Transfers
  - Inbound Wire Transfers
  - Wire Drawdown Requests
  - Inbound Wire Drawdown Requests
- name: Card Transfers
  tags:
  - Card Tokens
  - Card Push Transfers
  - Card Validations
- name: Check Deposits
  tags:
  - Check Deposits
  - Lockbox Addresses
  - Lockbox Recipients
  - Inbound Mail Items
- name: Cards
  tags:
  - Cards
  - Card Payments
  - Card Purchase Supplements
  - Card Disputes
  - Physical Cards
  - Digital Card Profiles
  - Physical Card Profiles
  - Digital Wallet Tokens
- name: Compliance
  tags:
  - Entities
  - Beneficial Owners
  - Supplemental Documents
  - Entity Onboarding Sessions
  - Programs
- name: Events and Webhooks
  tags:
  - Events
  - Event Subscriptions
  - Real-Time Decisions
- name: External Accounts
  tags:
  - Routing Numbers
  - External Accounts
- name: Files and Exports
  tags:
  - Account Statements
  - Files
  - File Links
  - Exports
- name: OAuth
  tags:
  - Groups
  - OAuth Applications
  - OAuth Connections
  - OAuth Tokens
- name: Intrafi
  tags:
  - IntraFi Account Enrollments
  - IntraFi Balances
  - IntraFi Exclusions
